### ISSUE TITLE
Vetur unable to type template

### ISSUE THREAD

**Issue by ycmjason** [vuejs/composition-api#104]
Vetur was able to type the variables in the template properly in VSCode with the previous `vue-function-api`.

Somehow it stops working after upgrading to `@vue/composition-api`. 

Please see the two branches:

1. Using `vue-function-api` https://github.com/ycmjason/perfect-colour
![image](https://user-images.githubusercontent.com/1251825/63941807-484c2180-ca64-11e9-96cc-ae6c56727667.png)

2. Using `@vue/composition-api` https://github.com/ycmjason/perfect-colour/tree/upgrade-to-composition-api
![image](https://user-images.githubusercontent.com/1251825/63941854-5ef27880-ca64-11e9-9a74-7e74e0e9a7d3.png)
The error reads:
```
Property 'answerRGB' does not exist on type 'never'.
```

Note on my VSCode config:
1.  `"vetur.useWorkspaceDependencies": true,`
2. `  "vetur.experimental.templateInterpolationService": true,`

**Comment by liximomo** [comment]
Fixed By https://github.com/vuejs/composition-api/commit/ac3581b2eb11f285584fc4ee1279cb2981e7be75

**Comment by lbssousa** [comment]
It still doesn't work perfectly as before. Although it doesn't give those `Property (...) does not exist on type 'never'.` errors anymore, now all variables referenced in `<template>` have their type inferred as `any`.

**Comment by victorgarciaesgi** [comment]
@lbssousa Any news on this? I'm getting all the unknown properties infered as `any` too using `defineComponent`

**Comment by pikax** [comment]
@victorgarciaesgi the types should work on the template.

I recommend asking on [Discord #typescript or #composition-api](https://vue.land), because it most likely one of the typescript with vue pitfalls.

**Comment by myknbani** [comment]
I stumbled on this as well.  Maybe this is the issue:  https://github.com/vuejs/vetur/issues/1874
