### ISSUE TITLE
Empty reactive object doesn't have reactivity for new keys 

### ISSUE THREAD

**Issue by roman0x58** [vuejs/composition-api#580]
Hi everyone! I'm using latest vue2 + composition-api (beta18) and I have an empty reactivity object in my component : 
```
const obj = reactive({})
```
later I set new props to this object using `set` :
```
set(obj, prop, value)
```
this should trigger changes and I'm expecting that my view will refresh, but it doesn't. So If I replace reactive by `ref({})` or initialize the reactive object with the `prop` it does work as expected.

sandbox example : https://codesandbox.io/s/late-river-lmze9

**Comment by iheyunfei** [comment]
fixed in #692 . @antfu maybe closes this one?

**Comment by tminich** [comment]
It still doesn't work correctly, at least not in computed. `del` seems to work (first click on 'Set by computed'), but `set` doesn't.
https://codesandbox.io/s/funny-agnesi-wr6i5

**Comment by shrpne** [comment]
I'm still experiencing the issue

https://codesandbox.io/s/beautiful-feather-qrjq4n?file=/src/components/TestCase.vue

**Comment by arielkuzminski** [comment]
Anybody got a solution for this? I need to create `refs` dynamically on the runtime (I don't know how much theres gonna be or how they are gonna be named). And then I need to do some filtering to them on user demand, and return still as reactive object so they affect original object.
